### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by Amrosx** [dshafer/sparql-redis-server#1]
if no how can I use sparql endpoint

**Comment by dshafer** [comment]
This is one-time work I did for a [term paper](https://github.com/dshafer/sparql-redis-server/blob/develop/paper/CS395T_DrewShafer_RedisSPARQLCluster.pdf) in grad school nearly a decade ago, and hasn't been touched since then.  There's no ongoing maintenance, no one other than me has ever used it, and I would not expect it to work well (or at all) except for being able to run a particular benchmark as it existed in 2013.
